name: potbelly
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  auth_buttons: 1.0.1+4
  auto_route: ^2.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: 
  cupertino_icons: ^1.0.0
  device_info: ^2.0.2
  dio: null
  firebase_messaging: 10.0.4
  firebase_core: 1.4.0
  firebase_auth: 3.0.1
  flutter_feather_icons: ^1.0.3
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^3.0.1+1
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_stripe: ^1.0.2
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  font_awesome_flutter: null
  geolocator: null
  google_fonts: null
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.0.4
  im_stepper: ^0.1.3
  image_picker: ^0.6.2
  image_viewer: ^1.5.0
  intl: null
  intro_slider: ^3.0.2
  location: ^4.3.0
  outline_material_icons: ^0.1.1
  path_provider: null
  place_picker: ^0.9.19-nullsafety
  popup_card: ^0.1.0
  provider: ^4.3.2+2
  rflutter_alert: ^2.0.2
  shared_preferences: null
  sign_in_with_apple: ^3.0.0
  skeleton_text: ^3.0.0
  the_apple_sign_in: ^1.1.1
  toast: null
  video_player: ^2.1.12
  video_thumbnail: null
  webview_flutter: ^2.0.10
  lottie: ^1.1.0
  flutter_hooks: ^0.18.0
  # flutter_swiper: ^1.1.6
  flutter_swiper_null_safety: ^1.0.2
  scroll_to_index: ^2.0.0
  maps_launcher: ^2.0.0
  url_launcher: ^6.0.9
  super_tooltip: ^1.0.1
  lazy_loading_list: ^1.0.1
  cached_network_image: ^3.1.0
  flutter_native_image: ^0.0.6
  flutter_gifimage: ^1.0.1
  time_formatter:
  
  # qr_code_scanner: ^0.5.2
  
  

#  flutter_launcher_icons: ^0.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0

#flutter_icons:
#  image_path: "assets/launcher/logo.png"
#  android: true
#  ios: true
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - assets/images/a_dot_burr.jpeg
  #  - assets/images/a_dot_ham.jpeg
  # or to include all assets from a directory do this:
  # assets:
  #   - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  assets:
    - assets/
    - assets/grovey/
    - assets/swipe/
    - assets/images/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/.15623.otf
          weight: 700
        - asset: assets/fonts/.15627.otf
    - family: Roboto
      fonts:
        - asset: assets/fonts/.15510.otf
        - asset: assets/fonts/.15498.otf
          weight: 700
    - family: .AppleSystemUIFont
      fonts:
        - asset: assets/fonts/SFNS.ttf
